### ISSUE TITLE
Sampling rate

### ISSUE THREAD

**Issue by philippberens** [codeneuro/spikefinder-python#5]
@freeman-lab 

For evaluation, we probably don't want to evaluate at the full 100 Hz that the signals are provided in. For the paper we used 25 Hz. Also, we want to be able to vary the resolution for making plots.

We have to find a way to pass as argument.

**Comment by freeman-lab** [comment]
This should now be being handled correctly, there's an argument `downsample` to the main `score` function with a default value of 4.
